version: '3'
services:
  database:
    image: postgis/postgis
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  app:
    container_name: app
    image: bankapi/app:1
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - database
#    'database' is replaced by database container ip
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DATABASE_NAME}
volumes:
  dbdata:
    driver: local